before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.
  
stages:
 - build
 - test

build:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Debug;Platform=win32
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Release;Platform=win32
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Super;Platform=win32
    - echo building x64...
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Debug;Platform=x64
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Release;Platform=x64
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Super;Platform=x64
  tags:
    - windows
    
test:
 stage: test
  script:
   - echo testing...
   - ../build/Win32/Debug/engine_UnitTester.exe
  tags:
   - windows 
