before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.

stages:
 - build


build:
  stage: build
  script:
    - echo building...
    -  robocopy ../build build *.xml *.exe *.dll /S /E
    -  ver > nul
  artifacts:
   paths:
    - build/
    - .xml
  tags:
    - windows
