before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.
  
stages:
 - build

build:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:"Clean;Build"
  tags:
    - windows