before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.

stages:
 - build
 - test


build:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Debug;Platform=win32
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Release;Platform=win32
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Super;Platform=win32
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Debug;Platform=x64
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Release;Platform=x64
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Super;Platform=x64
  artifacts:
   paths:
    - build/
    - .xml
  tags:
    - windows

test:
  stage: test
  script:
   - echo testing (win32 Debug)
   -  'cd "../build/win32/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (win32 Release)
   -  'cd "../Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (win32 Super)
   -  'cd "../Super/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Debug)
   -  'cd "../../x64/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Release)
   -  'cd "../Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Super)
   -  'cd "../Super/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
  tags:
   - windows
