before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.

stages:
 - build
 - test

build:build_3rdparty:
  stage: build
  script:
    - echo building x86...
    - msbuild 3rdparty/source/PhysX86.sln /t:build /p:Configuration=debug;Platform=x86
    - msbuild 3rdparty/source/PhysX86.sln /t:build /p:Configuration=checked;Platform=x86
    - msbuild 3rdparty/source/PhysX86.sln /t:build /p:Configuration=profile;Platform=x86
    - msbuild 3rdparty/source/PhysX86.sln /t:build /p:Configuration=release;Platform=x86
    - echo building x64...
    - msbuild 3rdparty/source/PhysX64.sln /t:build /p:Configuration=debug;Platform=x64
    - msbuild 3rdparty/source/PhysX64.sln /t:build /p:Configuration=checked;Platform=x64
    - msbuild 3rdparty/source/PhysX64.sln /t:build /p:Configuration=profile;Platform=x64
    - msbuild 3rdparty/source/PhysX64.sln /t:build /p:Configuration=release;Platform=x64
  artifacts:
   paths:
    - 3rdparty/bin/*.exe
    - 3rdparty/bin/*.pdb
  tags:
    - windows

build:win32_debug:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Debug;Platform=win32
    -  (robocopy ../build build *.xml *.exe *.dll *.pdb /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/Win32/Debug/*.exe
    - build/Win32/Debug/*.pdb
   dependencies:
    - build:build_3rdparty
  tags:
    - windows

build:win32_release:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Release;Platform=win32
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/Win32/Release/*.exe
   dependencies:
    - build:build_3rdparty
  tags:
    - windows

build:win32_super:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Super;Platform=win32
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/Win32/Super/*.exe
   dependencies:
    - build:build_3rdparty
  tags:
    - windows


build:x64_debug:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Debug;Platform=x64
    -  (robocopy ../build build *.xml *.exe *.dll *.pdb /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/x64/Debug/*.exe
    - build/x64/Debug/*.pdb
   dependencies:
    - build:build_3rdparty
  tags:
    - windows

build:x64_release:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Release;Platform=x64
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/x64/Release/*.exe
   dependencies:
    - build:build_3rdparty
  tags:
    - windows

build:x64_super:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Super;Platform=x64
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/x64/Super/*.exe
   dependencies:
    - build:build_3rdparty
  tags:
    - windows




test:win32_debug:
  stage: test
  script:
   - echo testing (win32 Debug)
   -  'cd "build/win32/Debug/'
   - engine_UnitTester.exe +fs_basepath "..\..\..\game_folder" -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/Win32/Debug/*.xml
  dependencies:
    - build:win32_debug
  tags:
   - windows
   - test

test:win32_release:
  stage: test
  script:
   - echo testing (win32 Release)
   -  'cd "build/win32/Release/'
   - engine_UnitTester.exe +fs_basepath "..\..\..\game_folder" -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/Win32/Release/*.xml
  dependencies:
    - build:win32_release
  tags:
   - windows
   - test

test:win32_super:
  stage: test
  script:
   - echo testing (win32 Super)
   -  'cd "build/win32/Super/'
   - engine_UnitTester.exe +fs_basepath "..\..\..\game_folder" -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/Win32/Super/*.xml
  dependencies:
    - build:win32_super
  tags:
   - windows
   - test

test:x64_debug:
  stage: test
  script:
   - echo testing (x64 Debug)
   -  'cd "build/x64/Debug/'
   - engine_UnitTester.exe +fs_basepath "..\..\..\game_folder" -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/x64/Debug/*.xml
  dependencies:
    - build:x64_debug
  tags:
   - windows
   - test

test:x64_release:
  stage: test
  script:
   - echo testing (x64 Release)
   -  'cd "build/x64/Release/'
   - engine_UnitTester.exe +fs_basepath "..\..\..\game_folder" -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/x64/Release/*.xml
  dependencies:
    - build:x64_release
  tags:
   - windows
   - test

test:x64_super:
  stage: test
  script:
   - echo testing (x64 Super)
   -  'cd "build/x64/Super/'
   - engine_UnitTester.exe +fs_basepath "..\..\..\game_folder" -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/x64/Super/*.xml
  dependencies:
    - build:x64_super
  tags:
   - windows
   - test

