before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.
  
stages:
 - build_win32
 - test_win32

build:
  stage: build_win32
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Debug;Platform=win32
 #   - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Release;Platform=win32
 #   - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Super;Platform=win32
  tags:
    - windows
  build:
  
stage: build_64
  script:
    - echo building x64...
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Debug;Platform=x64
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Release;Platform=x64
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Super;Platform=x64
  tags:
    - windows  
    
    
test:
  stage: test_win32
  script:
   - echo testing...
   - '../build/Win32/Debug/engine_UnitTester.exe'
  tags:
   - windows 