before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.
  
stages:
 - build
 - test

build_win32:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Debug;Platform=win32
 #   - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Release;Platform=win32
 #   - msbuild solutions/PulpEngine.sln /t:Clean;Rebuild /p:Configuration=Super;Platform=win32
  tags:
    - windows

test_win32:
  stage: test
  script:
   - echo testing...
   - "'../build/Win32/Debug/engine_UnitTester.exe'"
  tags:
   - windows 