before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.

stages:
 - build
 - test


build:win32_debug:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Debug;Platform=win32
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/Win32/Debug/*.exe
  tags:
    - windows

build:win32_release:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Release;Platform=win32
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/Win32/Release/*.exe
  tags:
    - windows


test:win32_debug:
  stage: test
  script:
   - echo testing (win32 Debug)
   -  'cd "build/win32/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/Win32/Debug/*.xml
  dependencies:
    - build:win32_debug
  tags:
   - windows


test:win32_release:
  stage: test
  script:
   - echo testing (win32 Release)
   -  'cd "build/win32/Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/Win32/Release/*.xml
  dependencies:
    - build:win32_release
  tags:
   - windows
