

stages:
 - build


build:win32_debug:
  stage: build
  script:
    - echo building...
    - echo $CI_COMMIT_SHA
    - echo ${CI_COMMIT_SHA}
  artifacts:
   expire_in: 1 week
   paths:
    - build/Win32/Debug/*.exe
    - build/Win32/Debug/*.dll
    - build/Win32/Debug/*.pdb
  tags:
    - windows
