before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.

stages:
 - build
 - test


build:
  stage: build
  script:
    - echo building...
    -  (robocopy ../build build *.xml *.exe *.dll /S /E) ^& exit 0
  artifacts:
   paths:
    - build/*.xml
  tags:
    - windows

test:
  stage: test
  script:
   - echo testing (win32 Debug)
   -  'cd "../build/win32/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (win32 Release)
   -  'cd "../Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (win32 Super)
   -  'cd "../Super/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Debug)
   -  'cd "../../x64/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Release)
   -  'cd "../Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Super)
   -  'cd "../Super/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
  tags:
   - windows
