before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - set
  - echo.

stages:
 - build
 - test


build:
  stage: build
  script:
    - echo building...
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   paths:
    - build/Win32/Debug/*.exe
    - build/Win32/Release/*.exe
    - build/Win32/Super/*.exe
    - build/x64/Debug/*.exe
    - build/x64/Release/*.exe
    - build/x64/Super/*.exe
  tags:
    - windows

test:
  stage: test
  script:
   - echo testing (win32 Debug)
   -  'cd "build/win32/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (win32 Release)
   -  'cd "../Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (win32 Super)
   -  'cd "../Super/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Debug)
   -  'cd "../../x64/Debug/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Release)
   -  'cd "../Release/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
   - echo testing (x64 Super)
   -  'cd "../Super/'
   - engine_UnitTester.exe -CI --gtest_output="xml:report.xml"
  artifacts:
    paths:
    - build/Win32/Debug/*.xml
    - build/Win32/Release/*.xml
    - build/Win32/Super/*.xml
    - build/x64/Debug/*.xml
    - build/x64/Release/*.xml
    - build/x64/Super/*.xml
  tags:
   - windows
