
variables:
  GIT_SSL_NO_VERIFY: "true"


before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'
  - echo.
  - 'set QTDIR=E:\Qt\Qt-5.10.1_64'
  - 'set PATH=%QTDIR%\bin;%PATH%'
  - set
  - echo.

stages:
 - build
 - pack


build:x64_super:
  stage: build
  script:
    - echo building...
    - msbuild solutions/PulpEngine.sln /t:build /p:Configuration=Super;Platform=x64
    -  (robocopy ../build build *.xml *.exe *.dll /S /E)  ^& exit /b 0
  artifacts:
   expire_in: 1 week
   paths:
    - build/x64/Super/*.exe
    - build/x64/Super/*.dll
  tags:
    - windows



pack:x64_super:
  stage: pack
  script:
   - 'cd "game_folder'
   - buildGame.bat
  artifacts:
    expire_in: 1 week
    paths:
    - game.7z
  dependencies:
    - build:x64_super
  tags:
   - windows
  when: manual