#pragma once

#ifndef X_PREPROCESSORCOMMAIF_H_
#define X_PREPROCESSORCOMMAIF_H_


#define X_PP_COMMA ,

#define X_PP_COMMA_EMPTY

#define X_PP_COMMA_IF(cond) X_PP_IF(cond, X_PP_COMMA, X_PP_COMMA_EMPTY)

#endif // X_PREPROCESSORCOMMAIF_H_
