// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assetdb.proto
#pragma warning(disable: 4244 4267 4996 4530 4577 4244 4018 4100 4125 4100 4125)

#ifndef PROTOBUF_assetdb_2eproto__INCLUDED
#define PROTOBUF_assetdb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Potato {
namespace ProtoBuf {
namespace AssetDB {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_assetdb_2eproto();
void protobuf_AssignDesc_assetdb_2eproto();
void protobuf_ShutdownFile_assetdb_2eproto();

class Reponse;
class AssetInfoReponse;
class AddAsset;
class DeleteAsset;
class RenameAsset;
class UpdateAsset;
class AssetExists;
class Request;

enum AssetType {
  MODEL = 1,
  ANIM = 2,
  MATERIAL = 3,
  IMG = 4
};
bool AssetType_IsValid(int value);
const AssetType AssetType_MIN = MODEL;
const AssetType AssetType_MAX = IMG;
const int AssetType_ARRAYSIZE = AssetType_MAX + 1;

const ::google::protobuf::EnumDescriptor* AssetType_descriptor();
inline const ::std::string& AssetType_Name(AssetType value) {
  return ::google::protobuf::internal::NameOfEnum(
    AssetType_descriptor(), value);
}
inline bool AssetType_Parse(
    const ::std::string& name, AssetType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AssetType>(
    AssetType_descriptor(), name, value);
}
enum Result {
  OK = 1,
  NOT_FOUND = 2,
  NAME_TAKEN = 3,
  UNCHANGED = 4,
  ERROR = 5
};
bool Result_IsValid(int value);
const Result Result_MIN = OK;
const Result Result_MAX = ERROR;
const int Result_ARRAYSIZE = Result_MAX + 1;

const ::google::protobuf::EnumDescriptor* Result_descriptor();
inline const ::std::string& Result_Name(Result value) {
  return ::google::protobuf::internal::NameOfEnum(
    Result_descriptor(), value);
}
inline bool Result_Parse(
    const ::std::string& name, Result* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Result>(
    Result_descriptor(), name, value);
}
// ===================================================================

class Reponse : public ::google::protobuf::Message {
 public:
  Reponse();
  virtual ~Reponse();

  Reponse(const Reponse& from);

  inline Reponse& operator=(const Reponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Reponse& default_instance();

  void Swap(Reponse* other);

  // implements Message ----------------------------------------------

  Reponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Reponse& from);
  void MergeFrom(const Reponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Potato.ProtoBuf.AssetDB.Result result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::Potato::ProtoBuf::AssetDB::Result result() const;
  inline void set_result(::Potato::ProtoBuf::AssetDB::Result value);

  // required string error = 2;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 2;
  inline const ::std::string& error() const;
  inline void set_error(const ::std::string& value);
  inline void set_error(const char* value);
  inline void set_error(const char* value, size_t size);
  inline ::std::string* mutable_error();
  inline ::std::string* release_error();
  inline void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.Reponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* error_;
  int result_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static Reponse* default_instance_;
};
// -------------------------------------------------------------------

class AssetInfoReponse : public ::google::protobuf::Message {
 public:
  AssetInfoReponse();
  virtual ~AssetInfoReponse();

  AssetInfoReponse(const AssetInfoReponse& from);

  inline AssetInfoReponse& operator=(const AssetInfoReponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssetInfoReponse& default_instance();

  void Swap(AssetInfoReponse* other);

  // implements Message ----------------------------------------------

  AssetInfoReponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AssetInfoReponse& from);
  void MergeFrom(const AssetInfoReponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .Potato.ProtoBuf.AssetDB.Result result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::Potato::ProtoBuf::AssetDB::Result result() const;
  inline void set_result(::Potato::ProtoBuf::AssetDB::Result value);

  // required string error = 2;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 2;
  inline const ::std::string& error() const;
  inline void set_error(const ::std::string& value);
  inline void set_error(const char* value);
  inline void set_error(const char* value, size_t size);
  inline ::std::string* mutable_error();
  inline ::std::string* release_error();
  inline void set_allocated_error(::std::string* error);

  // required string name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Potato.ProtoBuf.AssetDB.AssetType type = 4;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 4;
  inline ::Potato::ProtoBuf::AssetDB::AssetType type() const;
  inline void set_type(::Potato::ProtoBuf::AssetDB::AssetType value);

  // required uint32 id = 5;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 5;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required uint32 modId = 6;
  inline bool has_modid() const;
  inline void clear_modid();
  static const int kModIdFieldNumber = 6;
  inline ::google::protobuf::uint32 modid() const;
  inline void set_modid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.AssetInfoReponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_error();
  inline void clear_has_error();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_modid();
  inline void clear_has_modid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* error_;
  int result_;
  int type_;
  ::std::string* name_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 modid_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static AssetInfoReponse* default_instance_;
};
// -------------------------------------------------------------------

class AddAsset : public ::google::protobuf::Message {
 public:
  AddAsset();
  virtual ~AddAsset();

  AddAsset(const AddAsset& from);

  inline AddAsset& operator=(const AddAsset& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddAsset& default_instance();

  void Swap(AddAsset* other);

  // implements Message ----------------------------------------------

  AddAsset* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddAsset& from);
  void MergeFrom(const AddAsset& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::Potato::ProtoBuf::AssetDB::AssetType type() const;
  inline void set_type(::Potato::ProtoBuf::AssetDB::AssetType value);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.AddAsset)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  int type_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static AddAsset* default_instance_;
};
// -------------------------------------------------------------------

class DeleteAsset : public ::google::protobuf::Message {
 public:
  DeleteAsset();
  virtual ~DeleteAsset();

  DeleteAsset(const DeleteAsset& from);

  inline DeleteAsset& operator=(const DeleteAsset& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeleteAsset& default_instance();

  void Swap(DeleteAsset* other);

  // implements Message ----------------------------------------------

  DeleteAsset* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeleteAsset& from);
  void MergeFrom(const DeleteAsset& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::Potato::ProtoBuf::AssetDB::AssetType type() const;
  inline void set_type(::Potato::ProtoBuf::AssetDB::AssetType value);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.DeleteAsset)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  int type_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static DeleteAsset* default_instance_;
};
// -------------------------------------------------------------------

class RenameAsset : public ::google::protobuf::Message {
 public:
  RenameAsset();
  virtual ~RenameAsset();

  RenameAsset(const RenameAsset& from);

  inline RenameAsset& operator=(const RenameAsset& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RenameAsset& default_instance();

  void Swap(RenameAsset* other);

  // implements Message ----------------------------------------------

  RenameAsset* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RenameAsset& from);
  void MergeFrom(const RenameAsset& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required string newName = 2;
  inline bool has_newname() const;
  inline void clear_newname();
  static const int kNewNameFieldNumber = 2;
  inline const ::std::string& newname() const;
  inline void set_newname(const ::std::string& value);
  inline void set_newname(const char* value);
  inline void set_newname(const char* value, size_t size);
  inline ::std::string* mutable_newname();
  inline ::std::string* release_newname();
  inline void set_allocated_newname(::std::string* newname);

  // required .Potato.ProtoBuf.AssetDB.AssetType type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::Potato::ProtoBuf::AssetDB::AssetType type() const;
  inline void set_type(::Potato::ProtoBuf::AssetDB::AssetType value);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.RenameAsset)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_newname();
  inline void clear_has_newname();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* newname_;
  int type_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static RenameAsset* default_instance_;
};
// -------------------------------------------------------------------

class UpdateAsset : public ::google::protobuf::Message {
 public:
  UpdateAsset();
  virtual ~UpdateAsset();

  UpdateAsset(const UpdateAsset& from);

  inline UpdateAsset& operator=(const UpdateAsset& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateAsset& default_instance();

  void Swap(UpdateAsset* other);

  // implements Message ----------------------------------------------

  UpdateAsset* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateAsset& from);
  void MergeFrom(const UpdateAsset& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::Potato::ProtoBuf::AssetDB::AssetType type() const;
  inline void set_type(::Potato::ProtoBuf::AssetDB::AssetType value);

  // optional string args = 3;
  inline bool has_args() const;
  inline void clear_args();
  static const int kArgsFieldNumber = 3;
  inline const ::std::string& args() const;
  inline void set_args(const ::std::string& value);
  inline void set_args(const char* value);
  inline void set_args(const char* value, size_t size);
  inline ::std::string* mutable_args();
  inline ::std::string* release_args();
  inline void set_allocated_args(::std::string* args);

  // optional uint32 dataSize = 4;
  inline bool has_datasize() const;
  inline void clear_datasize();
  static const int kDataSizeFieldNumber = 4;
  inline ::google::protobuf::uint32 datasize() const;
  inline void set_datasize(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.UpdateAsset)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_args();
  inline void clear_has_args();
  inline void set_has_datasize();
  inline void clear_has_datasize();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* args_;
  int type_;
  ::google::protobuf::uint32 datasize_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static UpdateAsset* default_instance_;
};
// -------------------------------------------------------------------

class AssetExists : public ::google::protobuf::Message {
 public:
  AssetExists();
  virtual ~AssetExists();

  AssetExists(const AssetExists& from);

  inline AssetExists& operator=(const AssetExists& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AssetExists& default_instance();

  void Swap(AssetExists* other);

  // implements Message ----------------------------------------------

  AssetExists* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AssetExists& from);
  void MergeFrom(const AssetExists& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::Potato::ProtoBuf::AssetDB::AssetType type() const;
  inline void set_type(::Potato::ProtoBuf::AssetDB::AssetType value);

  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.AssetExists)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  int type_;
  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static AssetExists* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  enum MsgCase {
    kAdd = 1,
    kDel = 2,
    kRename = 3,
    kUpdate = 4,
    kExists = 5,
    MSG_NOT_SET = 0,
  };

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .Potato.ProtoBuf.AssetDB.AddAsset add = 1;
  inline bool has_add() const;
  inline void clear_add();
  static const int kAddFieldNumber = 1;
  inline const ::Potato::ProtoBuf::AssetDB::AddAsset& add() const;
  inline ::Potato::ProtoBuf::AssetDB::AddAsset* mutable_add();
  inline ::Potato::ProtoBuf::AssetDB::AddAsset* release_add();
  inline void set_allocated_add(::Potato::ProtoBuf::AssetDB::AddAsset* add);

  // optional .Potato.ProtoBuf.AssetDB.DeleteAsset del = 2;
  inline bool has_del() const;
  inline void clear_del();
  static const int kDelFieldNumber = 2;
  inline const ::Potato::ProtoBuf::AssetDB::DeleteAsset& del() const;
  inline ::Potato::ProtoBuf::AssetDB::DeleteAsset* mutable_del();
  inline ::Potato::ProtoBuf::AssetDB::DeleteAsset* release_del();
  inline void set_allocated_del(::Potato::ProtoBuf::AssetDB::DeleteAsset* del);

  // optional .Potato.ProtoBuf.AssetDB.RenameAsset rename = 3;
  inline bool has_rename() const;
  inline void clear_rename();
  static const int kRenameFieldNumber = 3;
  inline const ::Potato::ProtoBuf::AssetDB::RenameAsset& rename() const;
  inline ::Potato::ProtoBuf::AssetDB::RenameAsset* mutable_rename();
  inline ::Potato::ProtoBuf::AssetDB::RenameAsset* release_rename();
  inline void set_allocated_rename(::Potato::ProtoBuf::AssetDB::RenameAsset* rename);

  // optional .Potato.ProtoBuf.AssetDB.UpdateAsset update = 4;
  inline bool has_update() const;
  inline void clear_update();
  static const int kUpdateFieldNumber = 4;
  inline const ::Potato::ProtoBuf::AssetDB::UpdateAsset& update() const;
  inline ::Potato::ProtoBuf::AssetDB::UpdateAsset* mutable_update();
  inline ::Potato::ProtoBuf::AssetDB::UpdateAsset* release_update();
  inline void set_allocated_update(::Potato::ProtoBuf::AssetDB::UpdateAsset* update);

  // optional .Potato.ProtoBuf.AssetDB.AssetExists exists = 5;
  inline bool has_exists() const;
  inline void clear_exists();
  static const int kExistsFieldNumber = 5;
  inline const ::Potato::ProtoBuf::AssetDB::AssetExists& exists() const;
  inline ::Potato::ProtoBuf::AssetDB::AssetExists* mutable_exists();
  inline ::Potato::ProtoBuf::AssetDB::AssetExists* release_exists();
  inline void set_allocated_exists(::Potato::ProtoBuf::AssetDB::AssetExists* exists);

  inline MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:Potato.ProtoBuf.AssetDB.Request)
 private:
  inline void set_has_add();
  inline void set_has_del();
  inline void set_has_rename();
  inline void set_has_update();
  inline void set_has_exists();

  inline bool has_msg();
  void clear_msg();
  inline void clear_has_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  union MsgUnion {
    ::Potato::ProtoBuf::AssetDB::AddAsset* add_;
    ::Potato::ProtoBuf::AssetDB::DeleteAsset* del_;
    ::Potato::ProtoBuf::AssetDB::RenameAsset* rename_;
    ::Potato::ProtoBuf::AssetDB::UpdateAsset* update_;
    ::Potato::ProtoBuf::AssetDB::AssetExists* exists_;
  } msg_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_assetdb_2eproto();
  friend void protobuf_AssignDesc_assetdb_2eproto();
  friend void protobuf_ShutdownFile_assetdb_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// ===================================================================


// ===================================================================

// Reponse

// required .Potato.ProtoBuf.AssetDB.Result result = 1;
inline bool Reponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Reponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Reponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Reponse::clear_result() {
  result_ = 1;
  clear_has_result();
}
inline ::Potato::ProtoBuf::AssetDB::Result Reponse::result() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.Reponse.result)
  return static_cast< ::Potato::ProtoBuf::AssetDB::Result >(result_);
}
inline void Reponse::set_result(::Potato::ProtoBuf::AssetDB::Result value) {
  assert(::Potato::ProtoBuf::AssetDB::Result_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.Reponse.result)
}

// required string error = 2;
inline bool Reponse::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Reponse::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Reponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Reponse::clear_error() {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_->clear();
  }
  clear_has_error();
}
inline const ::std::string& Reponse::error() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.Reponse.error)
  return *error_;
}
inline void Reponse::set_error(const ::std::string& value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.Reponse.error)
}
inline void Reponse::set_error(const char* value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.Reponse.error)
}
inline void Reponse::set_error(const char* value, size_t size) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.Reponse.error)
}
inline ::std::string* Reponse::mutable_error() {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.Reponse.error)
  return error_;
}
inline ::std::string* Reponse::release_error() {
  clear_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_;
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Reponse::set_allocated_error(::std::string* error) {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_;
  }
  if (error) {
    set_has_error();
    error_ = error;
  } else {
    clear_has_error();
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.Reponse.error)
}

// -------------------------------------------------------------------

// AssetInfoReponse

// required .Potato.ProtoBuf.AssetDB.Result result = 1;
inline bool AssetInfoReponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AssetInfoReponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AssetInfoReponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AssetInfoReponse::clear_result() {
  result_ = 1;
  clear_has_result();
}
inline ::Potato::ProtoBuf::AssetDB::Result AssetInfoReponse::result() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetInfoReponse.result)
  return static_cast< ::Potato::ProtoBuf::AssetDB::Result >(result_);
}
inline void AssetInfoReponse::set_result(::Potato::ProtoBuf::AssetDB::Result value) {
  assert(::Potato::ProtoBuf::AssetDB::Result_IsValid(value));
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetInfoReponse.result)
}

// required string error = 2;
inline bool AssetInfoReponse::has_error() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AssetInfoReponse::set_has_error() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AssetInfoReponse::clear_has_error() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AssetInfoReponse::clear_error() {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_->clear();
  }
  clear_has_error();
}
inline const ::std::string& AssetInfoReponse::error() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetInfoReponse.error)
  return *error_;
}
inline void AssetInfoReponse::set_error(const ::std::string& value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetInfoReponse.error)
}
inline void AssetInfoReponse::set_error(const char* value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.AssetInfoReponse.error)
}
inline void AssetInfoReponse::set_error(const char* value, size_t size) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.AssetInfoReponse.error)
}
inline ::std::string* AssetInfoReponse::mutable_error() {
  set_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.AssetInfoReponse.error)
  return error_;
}
inline ::std::string* AssetInfoReponse::release_error() {
  clear_has_error();
  if (error_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_;
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AssetInfoReponse::set_allocated_error(::std::string* error) {
  if (error_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_;
  }
  if (error) {
    set_has_error();
    error_ = error;
  } else {
    clear_has_error();
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.AssetInfoReponse.error)
}

// required string name = 3;
inline bool AssetInfoReponse::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AssetInfoReponse::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AssetInfoReponse::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AssetInfoReponse::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& AssetInfoReponse::name() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetInfoReponse.name)
  return *name_;
}
inline void AssetInfoReponse::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetInfoReponse.name)
}
inline void AssetInfoReponse::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.AssetInfoReponse.name)
}
inline void AssetInfoReponse::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.AssetInfoReponse.name)
}
inline ::std::string* AssetInfoReponse::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.AssetInfoReponse.name)
  return name_;
}
inline ::std::string* AssetInfoReponse::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AssetInfoReponse::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.AssetInfoReponse.name)
}

// required .Potato.ProtoBuf.AssetDB.AssetType type = 4;
inline bool AssetInfoReponse::has_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AssetInfoReponse::set_has_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AssetInfoReponse::clear_has_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AssetInfoReponse::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Potato::ProtoBuf::AssetDB::AssetType AssetInfoReponse::type() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetInfoReponse.type)
  return static_cast< ::Potato::ProtoBuf::AssetDB::AssetType >(type_);
}
inline void AssetInfoReponse::set_type(::Potato::ProtoBuf::AssetDB::AssetType value) {
  assert(::Potato::ProtoBuf::AssetDB::AssetType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetInfoReponse.type)
}

// required uint32 id = 5;
inline bool AssetInfoReponse::has_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AssetInfoReponse::set_has_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AssetInfoReponse::clear_has_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AssetInfoReponse::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 AssetInfoReponse::id() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetInfoReponse.id)
  return id_;
}
inline void AssetInfoReponse::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetInfoReponse.id)
}

// required uint32 modId = 6;
inline bool AssetInfoReponse::has_modid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void AssetInfoReponse::set_has_modid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void AssetInfoReponse::clear_has_modid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void AssetInfoReponse::clear_modid() {
  modid_ = 0u;
  clear_has_modid();
}
inline ::google::protobuf::uint32 AssetInfoReponse::modid() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetInfoReponse.modId)
  return modid_;
}
inline void AssetInfoReponse::set_modid(::google::protobuf::uint32 value) {
  set_has_modid();
  modid_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetInfoReponse.modId)
}

// -------------------------------------------------------------------

// AddAsset

// required string name = 1;
inline bool AddAsset::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AddAsset::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AddAsset::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AddAsset::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& AddAsset::name() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AddAsset.name)
  return *name_;
}
inline void AddAsset::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AddAsset.name)
}
inline void AddAsset::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.AddAsset.name)
}
inline void AddAsset::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.AddAsset.name)
}
inline ::std::string* AddAsset::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.AddAsset.name)
  return name_;
}
inline ::std::string* AddAsset::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AddAsset::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.AddAsset.name)
}

// required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
inline bool AddAsset::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AddAsset::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AddAsset::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AddAsset::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Potato::ProtoBuf::AssetDB::AssetType AddAsset::type() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AddAsset.type)
  return static_cast< ::Potato::ProtoBuf::AssetDB::AssetType >(type_);
}
inline void AddAsset::set_type(::Potato::ProtoBuf::AssetDB::AssetType value) {
  assert(::Potato::ProtoBuf::AssetDB::AssetType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AddAsset.type)
}

// -------------------------------------------------------------------

// DeleteAsset

// required string name = 1;
inline bool DeleteAsset::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeleteAsset::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeleteAsset::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeleteAsset::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& DeleteAsset::name() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.DeleteAsset.name)
  return *name_;
}
inline void DeleteAsset::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.DeleteAsset.name)
}
inline void DeleteAsset::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.DeleteAsset.name)
}
inline void DeleteAsset::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.DeleteAsset.name)
}
inline ::std::string* DeleteAsset::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.DeleteAsset.name)
  return name_;
}
inline ::std::string* DeleteAsset::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DeleteAsset::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.DeleteAsset.name)
}

// required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
inline bool DeleteAsset::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeleteAsset::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeleteAsset::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeleteAsset::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Potato::ProtoBuf::AssetDB::AssetType DeleteAsset::type() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.DeleteAsset.type)
  return static_cast< ::Potato::ProtoBuf::AssetDB::AssetType >(type_);
}
inline void DeleteAsset::set_type(::Potato::ProtoBuf::AssetDB::AssetType value) {
  assert(::Potato::ProtoBuf::AssetDB::AssetType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.DeleteAsset.type)
}

// -------------------------------------------------------------------

// RenameAsset

// required string name = 1;
inline bool RenameAsset::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RenameAsset::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RenameAsset::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RenameAsset::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& RenameAsset::name() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.RenameAsset.name)
  return *name_;
}
inline void RenameAsset::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.RenameAsset.name)
}
inline void RenameAsset::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.RenameAsset.name)
}
inline void RenameAsset::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.RenameAsset.name)
}
inline ::std::string* RenameAsset::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.RenameAsset.name)
  return name_;
}
inline ::std::string* RenameAsset::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RenameAsset::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.RenameAsset.name)
}

// required string newName = 2;
inline bool RenameAsset::has_newname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RenameAsset::set_has_newname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RenameAsset::clear_has_newname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RenameAsset::clear_newname() {
  if (newname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    newname_->clear();
  }
  clear_has_newname();
}
inline const ::std::string& RenameAsset::newname() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.RenameAsset.newName)
  return *newname_;
}
inline void RenameAsset::set_newname(const ::std::string& value) {
  set_has_newname();
  if (newname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    newname_ = new ::std::string;
  }
  newname_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.RenameAsset.newName)
}
inline void RenameAsset::set_newname(const char* value) {
  set_has_newname();
  if (newname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    newname_ = new ::std::string;
  }
  newname_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.RenameAsset.newName)
}
inline void RenameAsset::set_newname(const char* value, size_t size) {
  set_has_newname();
  if (newname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    newname_ = new ::std::string;
  }
  newname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.RenameAsset.newName)
}
inline ::std::string* RenameAsset::mutable_newname() {
  set_has_newname();
  if (newname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    newname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.RenameAsset.newName)
  return newname_;
}
inline ::std::string* RenameAsset::release_newname() {
  clear_has_newname();
  if (newname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = newname_;
    newname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RenameAsset::set_allocated_newname(::std::string* newname) {
  if (newname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete newname_;
  }
  if (newname) {
    set_has_newname();
    newname_ = newname;
  } else {
    clear_has_newname();
    newname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.RenameAsset.newName)
}

// required .Potato.ProtoBuf.AssetDB.AssetType type = 3;
inline bool RenameAsset::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RenameAsset::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RenameAsset::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RenameAsset::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Potato::ProtoBuf::AssetDB::AssetType RenameAsset::type() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.RenameAsset.type)
  return static_cast< ::Potato::ProtoBuf::AssetDB::AssetType >(type_);
}
inline void RenameAsset::set_type(::Potato::ProtoBuf::AssetDB::AssetType value) {
  assert(::Potato::ProtoBuf::AssetDB::AssetType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.RenameAsset.type)
}

// -------------------------------------------------------------------

// UpdateAsset

// required string name = 1;
inline bool UpdateAsset::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateAsset::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateAsset::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateAsset::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& UpdateAsset::name() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.UpdateAsset.name)
  return *name_;
}
inline void UpdateAsset::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.UpdateAsset.name)
}
inline void UpdateAsset::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.UpdateAsset.name)
}
inline void UpdateAsset::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.UpdateAsset.name)
}
inline ::std::string* UpdateAsset::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.UpdateAsset.name)
  return name_;
}
inline ::std::string* UpdateAsset::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UpdateAsset::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.UpdateAsset.name)
}

// required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
inline bool UpdateAsset::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateAsset::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateAsset::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateAsset::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Potato::ProtoBuf::AssetDB::AssetType UpdateAsset::type() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.UpdateAsset.type)
  return static_cast< ::Potato::ProtoBuf::AssetDB::AssetType >(type_);
}
inline void UpdateAsset::set_type(::Potato::ProtoBuf::AssetDB::AssetType value) {
  assert(::Potato::ProtoBuf::AssetDB::AssetType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.UpdateAsset.type)
}

// optional string args = 3;
inline bool UpdateAsset::has_args() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UpdateAsset::set_has_args() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UpdateAsset::clear_has_args() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UpdateAsset::clear_args() {
  if (args_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    args_->clear();
  }
  clear_has_args();
}
inline const ::std::string& UpdateAsset::args() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.UpdateAsset.args)
  return *args_;
}
inline void UpdateAsset::set_args(const ::std::string& value) {
  set_has_args();
  if (args_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    args_ = new ::std::string;
  }
  args_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.UpdateAsset.args)
}
inline void UpdateAsset::set_args(const char* value) {
  set_has_args();
  if (args_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    args_ = new ::std::string;
  }
  args_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.UpdateAsset.args)
}
inline void UpdateAsset::set_args(const char* value, size_t size) {
  set_has_args();
  if (args_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    args_ = new ::std::string;
  }
  args_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.UpdateAsset.args)
}
inline ::std::string* UpdateAsset::mutable_args() {
  set_has_args();
  if (args_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    args_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.UpdateAsset.args)
  return args_;
}
inline ::std::string* UpdateAsset::release_args() {
  clear_has_args();
  if (args_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = args_;
    args_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UpdateAsset::set_allocated_args(::std::string* args) {
  if (args_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete args_;
  }
  if (args) {
    set_has_args();
    args_ = args;
  } else {
    clear_has_args();
    args_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.UpdateAsset.args)
}

// optional uint32 dataSize = 4;
inline bool UpdateAsset::has_datasize() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UpdateAsset::set_has_datasize() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UpdateAsset::clear_has_datasize() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UpdateAsset::clear_datasize() {
  datasize_ = 0u;
  clear_has_datasize();
}
inline ::google::protobuf::uint32 UpdateAsset::datasize() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.UpdateAsset.dataSize)
  return datasize_;
}
inline void UpdateAsset::set_datasize(::google::protobuf::uint32 value) {
  set_has_datasize();
  datasize_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.UpdateAsset.dataSize)
}

// -------------------------------------------------------------------

// AssetExists

// required string name = 1;
inline bool AssetExists::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AssetExists::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AssetExists::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AssetExists::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& AssetExists::name() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetExists.name)
  return *name_;
}
inline void AssetExists::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetExists.name)
}
inline void AssetExists::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Potato.ProtoBuf.AssetDB.AssetExists.name)
}
inline void AssetExists::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Potato.ProtoBuf.AssetDB.AssetExists.name)
}
inline ::std::string* AssetExists::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Potato.ProtoBuf.AssetDB.AssetExists.name)
  return name_;
}
inline ::std::string* AssetExists::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AssetExists::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Potato.ProtoBuf.AssetDB.AssetExists.name)
}

// required .Potato.ProtoBuf.AssetDB.AssetType type = 2;
inline bool AssetExists::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AssetExists::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AssetExists::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AssetExists::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Potato::ProtoBuf::AssetDB::AssetType AssetExists::type() const {
  // @@protoc_insertion_point(field_get:Potato.ProtoBuf.AssetDB.AssetExists.type)
  return static_cast< ::Potato::ProtoBuf::AssetDB::AssetType >(type_);
}
inline void AssetExists::set_type(::Potato::ProtoBuf::AssetDB::AssetType value) {
  assert(::Potato::ProtoBuf::AssetDB::AssetType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Potato.ProtoBuf.AssetDB.AssetExists.type)
}

// -------------------------------------------------------------------

// Request

// optional .Potato.ProtoBuf.AssetDB.AddAsset add = 1;
inline bool Request::has_add() const {
  return msg_case() == kAdd;
}
inline void Request::set_has_add() {
  _oneof_case_[0] = kAdd;
}
inline void Request::clear_add() {
  if (has_add()) {
    delete msg_.add_;
    clear_has_msg();
  }
}
inline const ::Potato::ProtoBuf::AssetDB::AddAsset& Request::add() const {
  return has_add() ? *msg_.add_
                      : ::Potato::ProtoBuf::AssetDB::AddAsset::default_instance();
}
inline ::Potato::ProtoBuf::AssetDB::AddAsset* Request::mutable_add() {
  if (!has_add()) {
    clear_msg();
    set_has_add();
    msg_.add_ = new ::Potato::ProtoBuf::AssetDB::AddAsset;
  }
  return msg_.add_;
}
inline ::Potato::ProtoBuf::AssetDB::AddAsset* Request::release_add() {
  if (has_add()) {
    clear_has_msg();
    ::Potato::ProtoBuf::AssetDB::AddAsset* temp = msg_.add_;
    msg_.add_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Request::set_allocated_add(::Potato::ProtoBuf::AssetDB::AddAsset* add) {
  clear_msg();
  if (add) {
    set_has_add();
    msg_.add_ = add;
  }
}

// optional .Potato.ProtoBuf.AssetDB.DeleteAsset del = 2;
inline bool Request::has_del() const {
  return msg_case() == kDel;
}
inline void Request::set_has_del() {
  _oneof_case_[0] = kDel;
}
inline void Request::clear_del() {
  if (has_del()) {
    delete msg_.del_;
    clear_has_msg();
  }
}
inline const ::Potato::ProtoBuf::AssetDB::DeleteAsset& Request::del() const {
  return has_del() ? *msg_.del_
                      : ::Potato::ProtoBuf::AssetDB::DeleteAsset::default_instance();
}
inline ::Potato::ProtoBuf::AssetDB::DeleteAsset* Request::mutable_del() {
  if (!has_del()) {
    clear_msg();
    set_has_del();
    msg_.del_ = new ::Potato::ProtoBuf::AssetDB::DeleteAsset;
  }
  return msg_.del_;
}
inline ::Potato::ProtoBuf::AssetDB::DeleteAsset* Request::release_del() {
  if (has_del()) {
    clear_has_msg();
    ::Potato::ProtoBuf::AssetDB::DeleteAsset* temp = msg_.del_;
    msg_.del_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Request::set_allocated_del(::Potato::ProtoBuf::AssetDB::DeleteAsset* del) {
  clear_msg();
  if (del) {
    set_has_del();
    msg_.del_ = del;
  }
}

// optional .Potato.ProtoBuf.AssetDB.RenameAsset rename = 3;
inline bool Request::has_rename() const {
  return msg_case() == kRename;
}
inline void Request::set_has_rename() {
  _oneof_case_[0] = kRename;
}
inline void Request::clear_rename() {
  if (has_rename()) {
    delete msg_.rename_;
    clear_has_msg();
  }
}
inline const ::Potato::ProtoBuf::AssetDB::RenameAsset& Request::rename() const {
  return has_rename() ? *msg_.rename_
                      : ::Potato::ProtoBuf::AssetDB::RenameAsset::default_instance();
}
inline ::Potato::ProtoBuf::AssetDB::RenameAsset* Request::mutable_rename() {
  if (!has_rename()) {
    clear_msg();
    set_has_rename();
    msg_.rename_ = new ::Potato::ProtoBuf::AssetDB::RenameAsset;
  }
  return msg_.rename_;
}
inline ::Potato::ProtoBuf::AssetDB::RenameAsset* Request::release_rename() {
  if (has_rename()) {
    clear_has_msg();
    ::Potato::ProtoBuf::AssetDB::RenameAsset* temp = msg_.rename_;
    msg_.rename_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Request::set_allocated_rename(::Potato::ProtoBuf::AssetDB::RenameAsset* rename) {
  clear_msg();
  if (rename) {
    set_has_rename();
    msg_.rename_ = rename;
  }
}

// optional .Potato.ProtoBuf.AssetDB.UpdateAsset update = 4;
inline bool Request::has_update() const {
  return msg_case() == kUpdate;
}
inline void Request::set_has_update() {
  _oneof_case_[0] = kUpdate;
}
inline void Request::clear_update() {
  if (has_update()) {
    delete msg_.update_;
    clear_has_msg();
  }
}
inline const ::Potato::ProtoBuf::AssetDB::UpdateAsset& Request::update() const {
  return has_update() ? *msg_.update_
                      : ::Potato::ProtoBuf::AssetDB::UpdateAsset::default_instance();
}
inline ::Potato::ProtoBuf::AssetDB::UpdateAsset* Request::mutable_update() {
  if (!has_update()) {
    clear_msg();
    set_has_update();
    msg_.update_ = new ::Potato::ProtoBuf::AssetDB::UpdateAsset;
  }
  return msg_.update_;
}
inline ::Potato::ProtoBuf::AssetDB::UpdateAsset* Request::release_update() {
  if (has_update()) {
    clear_has_msg();
    ::Potato::ProtoBuf::AssetDB::UpdateAsset* temp = msg_.update_;
    msg_.update_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Request::set_allocated_update(::Potato::ProtoBuf::AssetDB::UpdateAsset* update) {
  clear_msg();
  if (update) {
    set_has_update();
    msg_.update_ = update;
  }
}

// optional .Potato.ProtoBuf.AssetDB.AssetExists exists = 5;
inline bool Request::has_exists() const {
  return msg_case() == kExists;
}
inline void Request::set_has_exists() {
  _oneof_case_[0] = kExists;
}
inline void Request::clear_exists() {
  if (has_exists()) {
    delete msg_.exists_;
    clear_has_msg();
  }
}
inline const ::Potato::ProtoBuf::AssetDB::AssetExists& Request::exists() const {
  return has_exists() ? *msg_.exists_
                      : ::Potato::ProtoBuf::AssetDB::AssetExists::default_instance();
}
inline ::Potato::ProtoBuf::AssetDB::AssetExists* Request::mutable_exists() {
  if (!has_exists()) {
    clear_msg();
    set_has_exists();
    msg_.exists_ = new ::Potato::ProtoBuf::AssetDB::AssetExists;
  }
  return msg_.exists_;
}
inline ::Potato::ProtoBuf::AssetDB::AssetExists* Request::release_exists() {
  if (has_exists()) {
    clear_has_msg();
    ::Potato::ProtoBuf::AssetDB::AssetExists* temp = msg_.exists_;
    msg_.exists_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void Request::set_allocated_exists(::Potato::ProtoBuf::AssetDB::AssetExists* exists) {
  clear_msg();
  if (exists) {
    set_has_exists();
    msg_.exists_ = exists;
  }
}

inline bool Request::has_msg() {
  return msg_case() != MSG_NOT_SET;
}
inline void Request::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline Request::MsgCase Request::msg_case() const {
  return Request::MsgCase(_oneof_case_[0]);
}

// @@protoc_insertion_point(namespace_scope)

}  // namespace AssetDB
}  // namespace ProtoBuf
}  // namespace Potato

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Potato::ProtoBuf::AssetDB::AssetType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Potato::ProtoBuf::AssetDB::AssetType>() {
  return ::Potato::ProtoBuf::AssetDB::AssetType_descriptor();
}
template <> struct is_proto_enum< ::Potato::ProtoBuf::AssetDB::Result> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Potato::ProtoBuf::AssetDB::Result>() {
  return ::Potato::ProtoBuf::AssetDB::Result_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_assetdb_2eproto__INCLUDED
