#pragma once

#define X_VERSION_PP_STRINGIZE_HELPER(token) #token
#define X_VERSION_PP_STRINGIZE(str) X_VERSION_PP_STRINGIZE_HELPER(str)


#define X_TELEMETRY_NAME "Tom's Telemetry"
#define X_TELEMETRY_VERSION_MAJOR 0
#define X_TELEMETRY_VERSION_MINOR 1
#define X_TELEMETRY_VERSION_PATCH 0
#define X_TELEMETRY_VERSION_BUILD 0
#define X_TELEMETRY_VERSION_STR \
    X_VERSION_PP_STRINGIZE(X_TELEMETRY_VERSION_MAJOR) "." \
    X_VERSION_PP_STRINGIZE(X_TELEMETRY_VERSION_MINOR) "." \
    X_VERSION_PP_STRINGIZE(X_TELEMETRY_VERSION_PATCH) "." \
    X_VERSION_PP_STRINGIZE(X_TELEMETRY_VERSION_BUILD)


#define X_VER_COPYRIGHT_STR       "Copyright Tom Crowley (C) 2019"
#define X_VER_TRADEMARK_STR       ""
#define X_VER_COMPANY_STR         ""
