//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by xLib.rc
//
#define IDI_ENGINE_LOGO 101
#define IDI_FRAME_CLOSE 102
#define IDI_FRAME_MIN 103
#define IDI_FRAME_MAX 104
#define IDI_FRAME_RESTORE 105
#define IDI_FRAME_CLOSE_DULL 106
#define IDI_FRAME_MAX_DULL 107
#define IDI_FRAME_MIN_DULL 108
#define IDI_FRAME_RESTORE_DULL 109
#define IDI_FRAME_CLOSE_DISABLE 110
#define IDI_MAIN_ICON_FLUFFY 2001

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 111
#define _APS_NEXT_COMMAND_VALUE 40001
#define _APS_NEXT_CONTROL_VALUE 1001
#define _APS_NEXT_SYMED_VALUE 101
#endif
#endif
