

#include X_INCLUDE(Core/X_COMPILER/Compiler.h)


#if X_ENABLE_ASSERTIONS
#define X_NO_SWITCH_DEFAULT_ASSERT					X_ASSERT_UNREACHABLE(); break;
#else
#define X_NO_SWITCH_DEFAULT_ASSERT					X_NO_SWITCH_DEFAULT
#endif // !X_ENABLE_ASSERTIONS
